name: Docker

on:
  push:
    branches: [ master, release/* ]
    tags: [ '**' ]

env:
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

jobs:
  build:
    name: Build & Push
    runs-on: ubuntu-latest
    env:
      REPOSITORY_URL: ghcr.io
    steps:
      - id: string
        uses: ASzc/change-string-case-action@v5
        with: 
          string: ${{ github.repository_owner }}/alerta-webui
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm version
      - name: Variables
        id: vars
        run: echo "::set-output name=SHORT_COMMIT_ID::$(git rev-parse --short HEAD)"
      - name: Build image
        id: docker-build
        run: >-
          docker build
          -t ${{ steps.string.outputs.lowercase }}
          -t $REPOSITORY_URL/${{ steps.string.outputs.lowercase }}:$(cat VERSION)
          -t $REPOSITORY_URL/${{ steps.string.outputs.lowercase }}:${{ steps.vars.outputs.SHORT_COMMIT_ID }}
          -t $REPOSITORY_URL/${{ steps.string.outputs.lowercase }}:latest .
      - name: Docker Login
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REPOSITORY_URL }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish Image
        id: docker-push
        run: docker push --all-tags $REPOSITORY_URL/${{ steps.string.outputs.lowercase }}

      - uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
        if: failure()
